checkduration: "24h"
githubusername: "ArjenSchwarz"
githubtoken: "AQECAHgL87diS+gtOws91E0gf121Z+yeMlGmU2l8DBRhbwyFAAAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAybQK6Y6tkyJ7Yz638CARCAQ7nmYToCzd+8ZiFAWHOJH0EXfzBa1ZRrZEBwpPk+3YeIHqAL4n1NZ/JRSZ7L7L8efPS02JRdfH4l55SUNY4zUjoH9iE="
dateformat: "01-02-2006"
ifttttriggername: "dayone_github_collector"
iftttkey: "AQECAHgL87diS+gtOws91E0gf121Z+yeMlGmU2l8DBRhbwyFAAAAAIowgYcGCSqGSIb3DQEHBqB6MHgCAQAwcwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAw1Z0cZWDFjNpC/73wCARCARoZnSB73hWARMeHzJ7v166MysCYzgRxWsoRZZ5JbmoW00NvoGUXBWyknd59O/E6kPZlcBGyXH+s9qeooUwLluDDiunMxvn8="
kms: true
